[package]
name = "anystore-metastore-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anystore-domain.workspace = true
anystore-metastore.workspace = true
async-trait.workspace = true
chrono.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
tokio.workspace = true
